name: Tâche
description: >-
  Tâche technique ou implémentation contribuant
  à une user story
type: "Task"
body:
  - type: input
    id: task_story
    attributes:
      label: User Story
      description: Référence à la User Story
    validations:
      required: true
  - type: textarea
    id: task_description
    attributes:
      label: Tâche
      description: Ce qui doit être fait
    validations:
      required: true

  - type: textarea
    id: task_details
    attributes:
      label: Détails
      description: Détails techniques
    validations:
      required: false