name: Create release from tag

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'

jobs:
  release:
    uses: ZOS-IS/ToolBox/.github/workflows/reusable-releases-create_release_and_pr_from_new_tag.yml@main
    with:
      tag_name: ${{ github.ref_name }}
    secrets: inherit
