name: Send Slack message on new pull request ('dev-pull-requests' channel)

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  notify:
    if: >
      ((github.event.action == 'opened' && github.event.pull_request.draft == false) || (github.event.action == 'ready_for_review'))
      && (!contains(github.event.pull_request.title, '[SKIP-NOTICE]'))
    with:
      slack_channel: "dev-pull-requests"
      title: "Nouvelle pull request soumise"
      message: |
        *Dépôt* : ${{ github.event.repository.name }}
        *Titre* : ${{ github.event.pull_request.title }}
        *Auteur* : ${{ github.event.pull_request.user.login }}
        *Lien* : <${{ github.event.pull_request.html_url }}>
    secrets: inherit